### ISSUE TITLE
Monsters with spellcasting do not include the spells

### ISSUE THREAD

**Issue by Cphrampus** [Cphrampus/DnDAppFiles#294]
There are monsters that have spellcasting, either innate or learned that do not include the spells that they can cast, This makes it harder on someone using the app to run a monster to have to look up the spells

**Comment by Cphrampus** [comment]
This seems to be two problems. Some _do_ include the spells, but in lowercase, where the app expects exact matches, uppercase, comma separated. Or they do not include the spells at all, these are likely the ones I added and simply neglected.

This is also a notch towards having the generator normalize the data so that the "user"(data entry) doesn't need to worry about these little things that won't show up until deeply looked into, which slows down the overall entry process

**Comment by 153957** [comment]
Would you like assistance with this issue?
I can help fix:
- normalise Spellcasting sections, capitalisation, new lines, etc.
- capitalisation of existing references to spells to match those in the Spell lists.
- adding the `<spells>` and `<slots>` section for monsters where it is missing.

I can try to do this in the Python code, to see if I can perform the normalisation (automatically fix case in compendiums)

**Comment by Cphrampus** [comment]
Sure, if you want to take this on, go for it! I feel like the hardest part is finding the monsters that need to have spells added, but that can probably be accomplished by some form of search and elimination.
