### ISSUE TITLE
Make Bag of Holding a container

### ISSUE THREAD

**Issue by panosl** [Cphrampus/DnDAppFiles#368]
Is there a way to implement Bag of holding as a container object?

**Comment by Cphrampus** [comment]
Yes, this is possible and **should** not be hard to do. Hopefully it can simply be added as a Magic Item and get pulled in with that bundle.

However, there does not seem to be support for adding containers for the iOS version, as it tries to add the default items in the container instead, so this would only be available on Android.

This is a similar limitation to not being to add racial spells in the Android version.

**Comment by panosl** [comment]
Is the dev for Fight Club 5 active, should I reach him about seeing if he can amend the issue you mentioned?

Στάλθηκε από το iPhone μου

22 Μαΐ 2019, 1:34 πμ, ο χρήστης «Cody Phrampus <notifications@github.com>» έγραψε:

**Comment by Cphrampus** [comment]
I believe that there is still active development on the apps, so if you wish to reach out and try to get the different apps in sync in terms of features, that would be great

**Comment by panosl** [comment]
I already did, and linked them to this particular issue. Haven’t heard back, but let’s hope so.



Στάλθηκε από το iPhone μου

24 Μαΐ 2019, 12:58 πμ, ο χρήστης «Cody Phrampus <notifications@github.com>» έγραψε:
