### ISSUE TITLE
New damage types

### ISSUE THREAD

**Issue by panosl** [Cphrampus/DnDAppFiles#386]
New update for the iOS version:

![Screen Shot 2019-06-06 at 10 55 17 AM](https://user-images.githubusercontent.com/91211/59016333-b3ad9b00-8849-11e9-90bf-73fcde84f189.png)

**Comment by Cphrampus** [comment]
This also got released for the Android version, I had not seen the iOS update. Thanks, this will be a good thing to get updated/corrected for magical weapons
