### ISSUE TITLE
Having problems Importing Classes into Fight Club 5

### ISSUE THREAD

**Issue by Kamui2040** [Cphrampus/DnDAppFiles#412]
When trying to Import The Classes like Barbarian I get the error: Invalid autolevel at line 12 col 24.

**Comment by Cphrampus** [comment]
Are you trying to import the class file directly or import a compiled compendium?

The class files cannot be imported directly and none of the files should really be expected to work if they are, see README

**Comment by Kamui2040** [comment]
I am stupid, I was trying to import them directly, since I wasn't able to compile.

**Comment by Cphrampus** [comment]
I saw there was a compilation issue created as well, I am not in a position to investigate currently, but will look into that later tonight
